# Generated by Django 5.1.1 on 2025-03-11 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_comment'),
        ('base', '0004_message_title'),
    ]

    operations = [
    ]
